### ISSUE TITLE
Design: Dark & Light Theme

### ISSUE THREAD

**Issue by CentrixDE** [NodeLabIT/WebSuite-Core#11]
It would be nice to have multiple Themes preinstalled. Maybe a light and dark Theme with different Colours or styles.

**Comment by MarcTroll** [comment]
Unterschiedliche Designs werden ab v1.1.0 unterstützt werden

Zwischen einem Dark und einem Light-Design kann dann allerdings schon ab der 1.0.0 ausgewählt werden.
