### ISSUE TITLE
config.json - Beispiel hinzufügen

### ISSUE THREAD

**Issue by AlexanderMandera** [NodeLabIT/WebSuite-Core#32]
Man sollte eine beispielhafte config.json hinzufügen, da derzeit die WebSuite wegen der nicht vorhandenen Config abstürzt.

**Comment by MarcTroll** [comment]
Added in https://github.com/NodeLabIT/WebSuite-Core/commit/a8aa516a3e16b108b1fb65218526372759cc8f93
